name-template: '💡 v$NEXT_MINOR_VERSION'
tag-template: '$NEXT_MINOR_VERSION'
categories:
  - title: '🚀 기능 추가'
    label: 
      - '기능 추가'
  - title: '🚨 버그 수정'
    label:
      - '버그'
change-template: '- $TITLE #$NUMBER @$AUTHOR '
template: |
  $CHANGES
