name: Build_Project

on:
  push:
    branches: [ main, 0.2.1 ]
  pull_request:
    branches: [ main, 0.2.1 ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    name: Build for ${{ matrix.targetPlatform }}

    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - Android 
    
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: Library-

      - uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
          projectPath: Project_Politics

      - uses: actions/upload-artifact@v2
        with:
            name: Build-${{ matrix.targetPlatform }}
            path: build/${{ matrix.targetPlatform }}
